logging:
  level:
    io.github.carpl2.tidebid.trade: INFO

tidebid:
  messaging:
    rocketmq:
      topics:
        trade-events: tidebid-trade-events
        auction-events: tidebid-auction-events
        account-events: tidebid-account-events
        scheduled-commands: tidebid-scheduled-commands
      consumer-groups:
        auction-results: tidebid-trade-auction-v1
        account-results: tidebid-trade-account-v1
        payment-timeout: tidebid-trade-timeout-v1

info:
  config:
    service-source: nacos:tidebid-trade.yml
    revision: reliable-trade-03-messaging
