package io.github.carpl2.tidebid.security;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Loads the unencrypted PEM formats generated by {@code generate-jwt-keys.ps1}.
 */
public final class RsaPemKeyLoader {

    private static final long MAXIMUM_PEM_BYTES = 64 * 1024;

    private RsaPemKeyLoader() {
    }

    public static RSAPublicKey loadPublicKey(Path path) throws IOException, GeneralSecurityException {
        byte[] encoded = readPem(path, "PUBLIC KEY");
        var key = KeyFactory.getInstance("RSA").generatePublic(new X509EncodedKeySpec(encoded));
        if (!(key instanceof RSAPublicKey rsaKey)) {
            throw new InvalidKeySpecException("PEM does not contain an RSA public key");
        }
        return rsaKey;
    }

    public static RSAPrivateKey loadPrivateKey(Path path) throws IOException, GeneralSecurityException {
        byte[] encoded = readPem(path, "PRIVATE KEY");
        var key = KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(encoded));
        if (!(key instanceof RSAPrivateKey rsaKey)) {
            throw new InvalidKeySpecException("PEM does not contain an RSA private key");
        }
        return rsaKey;
    }

    public static RsaKeyPairMaterial loadKeyPair(Path privateKeyPath, Path publicKeyPath)
            throws IOException, GeneralSecurityException {
        return new RsaKeyPairMaterial(loadPublicKey(publicKeyPath), loadPrivateKey(privateKeyPath));
    }

    private static byte[] readPem(Path path, String label) throws IOException, InvalidKeySpecException {
        Path normalizedPath = path.toAbsolutePath().normalize();
        if (!Files.isRegularFile(normalizedPath)) {
            throw new IOException("JWT key file does not exist or is not a regular file: " + normalizedPath);
        }
        if (Files.size(normalizedPath) > MAXIMUM_PEM_BYTES) {
            throw new InvalidKeySpecException("JWT key file is unexpectedly large: " + normalizedPath);
        }

        String pem = Files.readString(normalizedPath, StandardCharsets.US_ASCII);
        Pattern pattern = Pattern.compile(
                "\\A\\s*-----BEGIN " + label + "-----\\s+([A-Za-z0-9+/=\\s]+?)\\s+-----END "
                        + label + "-----\\s*\\z"
        );
        Matcher matcher = pattern.matcher(pem);
        if (!matcher.matches()) {
            throw new InvalidKeySpecException("Expected an unencrypted " + label + " PEM file: " + normalizedPath);
        }
        try {
            return Base64.getDecoder().decode(matcher.group(1).replaceAll("\\s", ""));
        } catch (IllegalArgumentException exception) {
            throw new InvalidKeySpecException("JWT key file contains invalid Base64: " + normalizedPath, exception);
        }
    }
}
